### PR TITLE
feature(rules): Eslint 9 and flat config support

### LINKED ISSUE #93: Support ESLint 9.x
ESLint v9.0.0 is released !

It would be awesome to have official ESLint 9 support.
https://eslint.org/blog/2024/04/eslint-v9.0.0-released/

### PR DESCRIPTION
**Pull request by corbinu**
Updates to eslint 9 and the new flat file config system

 Resolves #93

### CODE REVIEW

**Comment by lukas-mertens** [comment]
@corbinu I think it would be nice to add some docs / an example on how to use the new flat config

**Comment by bryantmh** [comment]
This PR appears to be working and has been sitting here for awhile. Any chance of getting it merged even as a beta? I'm currently working on updating a Vue 2 project to Vue 3 that's already on eslint 9, and have had to manually make some of these changes to get it working even in compat mode.

**Comment by derHodrig** [comment]
@KaelWD @johnleider could you please apply necessary steps to publish this as a beta version? So we the community can test it and bring it to some sort of release?

This tool might be very handy but is not usable for eslint 9 users. With a beta we could at least test it and if it works we could migrate faster, if not, no problem its beta. What's your opinion?

**Comment by shimizukawa** [comment]
FYI: I'm using this PR code in my project, applying it via `@nuxt/eslint` as follows.

install
```
yarn add https://github.com/corbinu/eslint-plugin-vuetify/
```

`eslint.config.mjs`
```typescript
import vuetify from "eslint-plugin-vuetify/src/index.js";
import withNuxt from "./.nuxt/eslint.config.mjs";

export default withNuxt(
  {
    files: ['**/*.vue'],
    plugins: { vuetify },
    rules: {
      ...vuetify.configs.base.rules,
     'vuetify/no-deprecated-classes': '<SOME-VALUE>',
    },
  },
);
```

**Comment by SmootherSpike** [comment]
any updates when this will be merged?

**Review by johnleider — APPROVED** [review]

**Comment by corbinu** [comment]
Hello,

I am not going to be moving forward with using this plugin so if anybody else wants to take over the PR they are welcome to.

Corbin Uselton

**Comment by corbinu** [comment]
@shimizukawa Here is the one request I was given. Sorry that I can't do this right now.

> @corbinu I think it would be nice to add some docs / an example on how to use the new flat config. You should probably adopt the README a bit

**Comment by shimizukawa** [comment]
@corbinu  OK, then. I'll submit another PR to update the documentation.
@johnleider I think this PR can be merged without waiting for the documentation to be updated.

**Comment by shimizukawa** [comment]
@corbinu @johnleider I have created a PR  #101 for documentation update. Please check it out.

**Comment by leequarella** [comment]
Any updates on merging?

**Comment by johnleider** [comment]
> Any updates on merging?

I've pinged @KaelWD. With him being the primary developer on this plugin, I was really hoping for his final approval before merging.

**Pull request closed without merging**
