### PR TITLE
fix(VCheckbox): allow hint prop

### LINKED ISSUE #66: `v-checkbox` hint prop wrongly assumed as deprecated
Using the hint prop on `v-checkbox` results in a eslint error that states that hint is deprecated, which is not the case: https://vuetifyjs.com/en/api/v-checkbox/#props-hint

### PR DESCRIPTION
**Pull request by mtdvlpr**
Closes #66

### CODE REVIEW

**Comment by KaelWD** [comment]
`dense` reduced height, vertical margins, and icon size; `density` just reduces height.

**Comment by mtdvlpr** [comment]
Then density is still desired if dense was previously used.

**Comment by KaelWD** [comment]
I guess the idea was that because there isn't an exact replacement it was better to just highlight it as something that probably needs to be fixed manually.

**Comment by mtdvlpr** [comment]
That's valid I guess

**Pull request merged**
